// Local Host
### Get all contacts
GET http://localhost:3000/movies

####User contat by id 


GET http://localhost:3000/movies/67903d741666c20fb2ccf443


### POST - create contact
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

{
    "title": "Romero",
  "genre": "Science Fiction",
  "duration": 148,
  "releaseDate": "2008-07-18T00:00:00.000Z",
  "director": "Christopher Nolan",
  "cast": [
    "Leonardo DiCaprio",
    "Joseph Gordon-Levitt",
    "Elliot Page",
    "Tom Hardy"
  ],
  "cinemaId": "679018f6be2c5a72e7e3e87b"
  }
### PUT - update contact

   PUT http://localhost:3000/cinemas/679418ab75ee5bb84fa7b5d9 HTTP/1.1
content-type: application/json

{
    "name": "Cine Arte Oaxaca",
    "location": "Oaxaca, Oaxaca",
    "capacity": 25,
    "openingHours": "12:00 PM - 10:00 PM",
    "amenities": ["Indie Movies", "Coffee Shop"],
    "contactNumber": "9512345678",
    "isOpen": true
  }


### DELETE contact
DELETE http://localhost:3000/users/6786c0faa8840b394de35012 HTTP/1.1




// REnder 
### Get all contacts
GET https://project2-p1-cse341.onrender.com/movies


### POST - create contact
POST https://project2-p1-cse341.onrender.com/movies HTTP/1.1
content-type: application/json

{
  "title": "Romero",
    "genre": "Science Fictidfdfdon",
    "duration": 148,
    "releaseDate": "2010-07-16T00:00:00.000Z",
    "director": "Christopher Noldfdfan",
    "cast": [
      "Leonardo DiCaprdfdio",
      "Joseph Gordon-Ldfdevitt",
      "Elliot Pagdfe",
      "Tom Hdfardy"
    ],
    "cinemaId": "679018f6be2c5a72e7e3e"
  }
### PUT - update contact
PUT https://project2-p1-cse341.onrender.com/movies/67913b0847dedaf6daa75cee HTTP/1.1
content-type: application/json

{
    "name": "Cine Arte Oaxaca",
    "location": "Oaxaca, Oaxaca",
    "capacity": 90,
    "openingHours": "12:00 PM - 10:00 PM",
    "amenities": ["Indie Movies", "Coffee Shop"],
    "contactNumber": "9512345678",
    "isOpen": true
  }
### DELETE contact
DELETE https://project2-p1-cse341.onrender.com/movies/67913b0847dedaf6daa75cee HTTP/1.1
